// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIxiK537atUNqC0s6uB3qZoHK-dZvxJ8',
    appId: '1:906966999723:android:2805de43ae0a2bf7be8dee',
    messagingSenderId: '906966999723',
    projectId: 'fitness-tracker-5f901',
    storageBucket: 'fitness-tracker-5f901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2tO_3JXN6cea1uVaCcG2cwc4l_gbUH9M',
    appId: '1:906966999723:ios:5ca7b6461a303504be8dee',
    messagingSenderId: '906966999723',
    projectId: 'fitness-tracker-5f901',
    storageBucket: 'fitness-tracker-5f901.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc6Tm4g48n0GSk-iTuCKLVEw029r5QFgg',
    appId: '1:906966999723:web:cf82998c267669d3be8dee',
    messagingSenderId: '906966999723',
    projectId: 'fitness-tracker-5f901',
    authDomain: 'fitness-tracker-5f901.firebaseapp.com',
    storageBucket: 'fitness-tracker-5f901.firebasestorage.app',
    measurementId: 'G-19B7M245RT',
  );
}
